baseurl = "https://username.github.io"
languageCode = "en-us"
title = "Beautiful Hugo"
theme = "beautifulhugo"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  subtitle = "Build a beautiful and simple website in minutes"
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  commit = false

[Author]
  name = "Some Person"
  email = "youremail@domain.com"
  facebook = "username"
  github = "username"
  twitter = "username"
  linkedin = "pub/username/X/YYY/ZZZ"
  stackoverflow = "users/XXXXXXX/username"
  soundcloud = "username"
  wikipedia = "User:username"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 2